DROP TABLE "ALARM" CASCADE CONSTRAINTS;
DROP TABLE "ASK" CASCADE CONSTRAINTS;
DROP TABLE "BOARD" CASCADE CONSTRAINTS;
DROP TABLE "BOARD_IMG" CASCADE CONSTRAINTS;
DROP TABLE "CHAT_ROOM" CASCADE CONSTRAINTS;
DROP TABLE "COMMENT" CASCADE CONSTRAINTS;
DROP TABLE "DOG" CASCADE CONSTRAINTS;
DROP TABLE "HISTORY" CASCADE CONSTRAINTS;
DROP TABLE "INFO" CASCADE CONSTRAINTS;
DROP TABLE "LIKE" CASCADE CONSTRAINTS;
DROP TABLE "MEMO" CASCADE CONSTRAINTS;
DROP TABLE "MESSAGE" CASCADE CONSTRAINTS;
DROP TABLE "NOTICE" CASCADE CONSTRAINTS;
DROP TABLE "PRODUCT" CASCADE CONSTRAINTS;
DROP TABLE "PROFILE_IMG" CASCADE CONSTRAINTS;
DROP TABLE "REPLY" CASCADE CONSTRAINTS;
DROP TABLE "REPORT" CASCADE CONSTRAINTS;
DROP TABLE "USER" CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_ALARM;
DROP SEQUENCE SEQ_ASK;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_BOARD_IMG;
DROP SEQUENCE SEQ_CHAT_ROOM;
DROP SEQUENCE SEQ_COMMENT;
DROP SEQUENCE SEQ_DOG;
DROP SEQUENCE SEQ_HISTORY;
DROP SEQUENCE SEQ_INFO;
DROP SEQUENCE SEQ_LIKE;
DROP SEQUENCE SEQ_MEMO;
DROP SEQUENCE SEQ_MESSAGE;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_PROFILE_IMG;
DROP SEQUENCE SEQ_REPLY;
DROP SEQUENCE SEQ_REPORT;
DROP SEQUENCE SEQ_USER;

CREATE SEQUENCE SEQ_ALARM;
CREATE SEQUENCE SEQ_ASK;
CREATE SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_BOARD_IMG;
CREATE SEQUENCE SEQ_CHAT_ROOM;
CREATE SEQUENCE SEQ_COMMENT;
CREATE SEQUENCE SEQ_DOG;
CREATE SEQUENCE SEQ_HISTORY;
CREATE SEQUENCE SEQ_INFO;
CREATE SEQUENCE SEQ_LIKE;
CREATE SEQUENCE SEQ_MEMO;
CREATE SEQUENCE SEQ_MESSAGE;
CREATE SEQUENCE SEQ_NOTICE;
CREATE SEQUENCE SEQ_PRODUCT;
CREATE SEQUENCE SEQ_PROFILE_IMG;
CREATE SEQUENCE SEQ_REPLY;
CREATE SEQUENCE SEQ_REPORT;
CREATE SEQUENCE SEQ_USER;

-------------------- CREATE TABLE --------------------
CREATE TABLE "ASK" (
	"ASK_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(2000)		NOT NULL,
	"RES_CONTENT"	VARCHAR2(2000)		NULL,
	"STATUS"	CHAR(2)	DEFAULT 'N'	NOT NULL,
	"ASK_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"RES_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"TITLE"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "ALARM" (
	"ALARM_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"FROM_USER_NO"	NUMBER		NULL,
	"CONTENT"	VARCHAR2(1000)	DEFAULT '새로운 알림'	NOT NULL,
	"STATUS"	CHAR(2)	DEFAULT 'N'	NOT NULL,
	"ALARM_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ALARM_TYPE"	CHAR(2)		NOT NULL,
	"CHAT_ROOM_NO"	NUMBER		NULL,
	"BOARD_NO"	NUMBER		NULL,
	"COMMENT_NO"	NUMBER		NULL
);

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(100)		NOT NULL,
	"CONTENT"	VARCHAR2(2000)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"VIEWS"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_STATUS"	CHAR(2)	DEFAULT 'Y'	NOT NULL,
	"BOARD_CATEGORY"	CHAR(2)		NOT NULL,
	"DETAIL_STATUS"	CHAR(2)		NULL,
	"LIKES"	NUMBER	DEFAULT 0	NOT NULL
);

CREATE TABLE "BOARD_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(100)		NULL,
	"CHAGNE_NAME"	VARCHAR2(100)		NULL
);

CREATE TABLE "CHAT_ROOM" (
	"CHAT_ROOM_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"STATUS"	CHAR(2)	DEFAULT 'Y'	NOT NULL
);

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(100)		NULL,
	"COMMENT_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"STATUS"	CHAR(2)	DEFAULT 'Y'	NULL
);

CREATE TABLE "DOG" (
	"DOG_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"DOG_NAME"	VARCHAR2(50)		NOT NULL,
	"BREED"	VARCHAR2(50)	DEFAULT '모름'	NOT NULL,
	"GENDER"	CHAR(2)	DEFAULT 'N'	NOT NULL,
	"BIRTHDAY"	DATE		NULL,
	"NOTE"	VARCHAR2(1000)		NULL,
	"PROFILE_NO"	NUMBER		NULL
);

CREATE TABLE "HISTORY" (
	"HISTORY_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"POINT"	NUMBER	DEFAULT 100	NOT NULL,
	"POINT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CONTENT"	VARCHAR2(200)		NULL
);

CREATE TABLE "INFO" (
	"INFO_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(2000)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"INFO_IMG"	VARCHAR2(500)		NULL
);

CREATE TABLE "LIKE" (
	"LIKE_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"LIKE_TYPE"	CHAR(2)		NOT NULL,
	"BOARD_NO"	NUMBER		NULL,
	"INFO_NO"	NUMBER		NULL,
	"ITEM_NO"	NUMBER		NULL
);

CREATE TABLE "MEMO" (
	"MEMO_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(200)		NOT NULL
);

CREATE TABLE "MESSAGE" (
	"MESSAGE_NO"	NUMBER		NOT NULL,
	"CHAT_ROOM_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(2000)		NOT NULL,
	"MESSAGE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(2000)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"INFO_IMG"	VARCHAR2(500)		NULL
);

CREATE TABLE "PRODUCT" (
	"PRODUCT_NO"	NUMBER		NOT NULL,
	"PRICE"	NUMBER		NOT NULL,
	"QTY"	NUMBER	DEFAULT 0	NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NULL,
	"STATUS"	CHAR(2)	DEFAULT 'Y'	NOT NULL,
	"LIKES"	NUMBER	DEFAULT 0	NOT NULL
);

CREATE TABLE "PROFILE_IMG" (
	"PROFILE_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(100) NOT NULL,
	"CHANGE_NAME"	VARCHAR2(100) NOT NULL
);

CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"COMMENT_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(100)		NOT NULL,
	"REPLY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"STATUS"	CHAR(2)	DEFAULT 'Y'	NULL
);

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"CATEGORY"	VARCHAR2(100)		NOT NULL,
	"CONTENT"	VARCHAR2(2000)		NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REPORT_TYPE"	CHAR(2)		NOT NULL,
	"BOARD_NO"	NUMBER		NULL,
	"CHAT_ROOM_NO"	NUMBER		NULL,
	"COMMENT_NO"	NUMBER		NULL,
	"REPLY_NO"	NUMBER		NULL
);

CREATE TABLE "USER" (
	"USER_NO"	NUMBER		NOT NULL,
	"EMAIL"	VARCHAR2(100) NOT NULL UNIQUE,
	"PWD"	VARCHAR2(500)		NOT NULL,
	"USER_NAME"	VARCHAR2(50)		NOT NULL,
	"NICK_NAME"	VARCHAR2(50) NOT NULL UNIQUE,
	"PHONE"	VARCHAR2(13) NOT NULL UNIQUE,
	"ADDRESS"	VARCHAR2(1000)		NULL,
	"STATUS"	CHAR(2)	DEFAULT 'Y'	NOT NULL,
	"POINTS"	NUMBER	DEFAULT 0	NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PROFILE_NO"	NUMBER		NULL
);


-------------------- CONSTRAINT --------------------
-------------------- PK --------------------
ALTER TABLE "ALARM" ADD CONSTRAINT "PK_ALARM" PRIMARY KEY (
	"ALARM_NO"
);
ALTER TABLE "ASK" ADD CONSTRAINT "PK_ASK" PRIMARY KEY (
	"ASK_NO"
);
ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);
ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"IMG_NO"
);
ALTER TABLE "CHAT_ROOM" ADD CONSTRAINT "PK_CHAT_ROOM" PRIMARY KEY (
	"CHAT_ROOM_NO"
);
ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);
ALTER TABLE "DOG" ADD CONSTRAINT "PK_DOG" PRIMARY KEY (
	"DOG_NO"
);
ALTER TABLE "HISTORY" ADD CONSTRAINT "PK_HISTORY" PRIMARY KEY (
	"HISTORY_NO"
);
ALTER TABLE "INFO" ADD CONSTRAINT "PK_INFO" PRIMARY KEY (
	"INFO_NO"
);
ALTER TABLE "LIKE" ADD CONSTRAINT "PK_LIKE" PRIMARY KEY (
	"LIKE_NO"
);
ALTER TABLE "MEMO" ADD CONSTRAINT "PK_MEMO" PRIMARY KEY (
	"MEMO_NO"
);
ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
	"MESSAGE_NO"
);
ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);
ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRODUCT_NO"
);
ALTER TABLE "PROFILE_IMG" ADD CONSTRAINT "PK_PROFILE_IMG" PRIMARY KEY (
	"PROFILE_NO"
);
ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"REPLY_NO"
);
ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);
ALTER TABLE "USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY (
	"USER_NO"
);

-------------------- FK --------------------
----- FK없는 테이블 4개(INFO, NOTICE, PRODUCT, PROFILE_IMG)
----- ALARM
ALTER TABLE "ALARM" ADD CONSTRAINT "FK_USER_TO_ALARM_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
ALTER TABLE "ALARM" ADD CONSTRAINT "FK_USER_TO_ALARM_2" FOREIGN KEY (
	"FROM_USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
ALTER TABLE "ALARM" ADD CONSTRAINT "FK_CHAT_ROOM_TO_ALARM_1" FOREIGN KEY (
	"CHAT_ROOM_NO"
)
REFERENCES "CHAT_ROOM" (
	"CHAT_ROOM_NO"
);
ALTER TABLE "ALARM" ADD CONSTRAINT "FK_BOARD_TO_ALARM_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);
ALTER TABLE "ALARM" ADD CONSTRAINT "FK_COMMENT_TO_ALARM_1" FOREIGN KEY (
	"COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);
----- ASK
ALTER TABLE "ASK" ADD CONSTRAINT "FK_USER_TO_ASK_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- BOARD
ALTER TABLE "BOARD" ADD CONSTRAINT "FK_USER_TO_BOARD_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- BOARD_IMG
ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);
----- CHAT_ROOM
ALTER TABLE "CHAT_ROOM" ADD CONSTRAINT "FK_USER_TO_CHAT_ROOM_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- COMMENT
ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);
ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_USER_TO_COMMENT_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- DOG
ALTER TABLE "DOG" ADD CONSTRAINT "FK_USER_TO_DOG_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
ALTER TABLE "DOG" ADD CONSTRAINT "FK_PROFILE_IMG_TO_DOG_1" FOREIGN KEY (
	"PROFILE_NO"
)
REFERENCES "PROFILE_IMG" (
	"PROFILE_NO"
);
----- HISTORY
ALTER TABLE "HISTORY" ADD CONSTRAINT "FK_USER_TO_HISTORY_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- LIKE
ALTER TABLE "LIKE" ADD CONSTRAINT "FK_USER_TO_LIKE_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
ALTER TABLE "LIKE" ADD CONSTRAINT "FK_BOARD_TO_LIKE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);
ALTER TABLE "LIKE" ADD CONSTRAINT "FK_INFO_TO_LIKE_1" FOREIGN KEY (
	"INFO_NO"
)
REFERENCES "INFO" (
	"INFO_NO"
);
ALTER TABLE "LIKE" ADD CONSTRAINT "FK_PRODUCT_TO_LIKE_1" FOREIGN KEY (
	"ITEM_NO"
)
REFERENCES "PRODUCT" (
	"PRODUCT_NO"
);
----- MEMO
ALTER TABLE "MEMO" ADD CONSTRAINT "FK_USER_TO_MEMO_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- MESSAGE
ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_CHAT_ROOM_TO_MESSAGE_1" FOREIGN KEY (
	"CHAT_ROOM_NO"
)
REFERENCES "CHAT_ROOM" (
	"CHAT_ROOM_NO"
);
ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_USER_TO_MESSAGE_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- REPLY
ALTER TABLE "REPLY" ADD CONSTRAINT "FK_COMMENT_TO_REPLY_1" FOREIGN KEY (
	"COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);
ALTER TABLE "REPLY" ADD CONSTRAINT "FK_USER_TO_REPLY_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- REPORT
ALTER TABLE "REPORT" ADD CONSTRAINT "FK_USER_TO_REPORT_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
ALTER TABLE "REPORT" ADD CONSTRAINT "FK_BOARD_TO_REPORT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);
ALTER TABLE "REPORT" ADD CONSTRAINT "FK_CHAT_ROOM_TO_REPORT_1" FOREIGN KEY (
	"CHAT_ROOM_NO"
)
REFERENCES "CHAT_ROOM" (
	"CHAT_ROOM_NO"
);
ALTER TABLE "REPORT" ADD CONSTRAINT "FK_COMMENT_TO_REPORT_1" FOREIGN KEY (
	"COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);
ALTER TABLE "REPORT" ADD CONSTRAINT "FK_REPLY_TO_REPORT_1" FOREIGN KEY (
	"REPLY_NO"
)
REFERENCES "REPLY" (
	"REPLY_NO"
);
----- USER
ALTER TABLE "USER" ADD CONSTRAINT "FK_PROFILE_IMG_TO_USER_1" FOREIGN KEY (
	"PROFILE_NO"
)
REFERENCES "PROFILE_IMG" (
	"PROFILE_NO"
);


-------------------- COMMENT --------------------
-- ALARM
COMMENT ON COLUMN "ALARM"."ALARM_NO" IS 'SEQ_ALARM';
COMMENT ON COLUMN "ALARM"."USER_NO" IS '알람 받을 회원 번호';
COMMENT ON COLUMN "ALARM"."FROM_USER_NO" IS '알람을 발생시킨 회원 번호';
COMMENT ON COLUMN "ALARM"."CONTENT" IS '한글 333자';
COMMENT ON COLUMN "ALARM"."STATUS" IS 
'N - 안읽음
Y - 읽음';
COMMENT ON COLUMN "ALARM"."ALARM_DATE" IS '알람 발생 시간';
COMMENT ON COLUMN "ALARM"."ALARM_TYPE" IS 
'C - 댓글 (BOARD)
L - 좋아요 (BOARD)
R - 대댓글 (COMMENT)
M - 채팅메세지 (CHAT_ROOM)
A - 관리자';
COMMENT ON COLUMN "ALARM"."CHAT_ROOM_NO" IS '알림이 온 채팅방 번호';
COMMENT ON COLUMN "ALARM"."BOARD_NO" IS '알림이 온 게시글 번호(좋아요, 댓글)';
COMMENT ON COLUMN "ALARM"."COMMENT_NO" IS '대댓글이 달린 댓글 번호';

-- ASK
COMMENT ON COLUMN "ASK"."ASK_NO" IS 'SEQ_ASK';
COMMENT ON COLUMN "ASK"."USER_NO" IS '문의한 회원 번호';
COMMENT ON COLUMN "ASK"."CONTENT" IS '한글 666자';
COMMENT ON COLUMN "ASK"."STATUS" IS 
'Y - 답변완료
N - 미완료';

COMMENT ON COLUMN "ASK"."TITLE" IS '한글 33자';

-- BOARD
COMMENT ON COLUMN "BOARD"."BOARD_NO" IS 'SEQ_BOARD';
COMMENT ON COLUMN "BOARD"."USER_NO" IS '게시글 작성한 회원 번호';
COMMENT ON COLUMN "BOARD"."TITLE" IS '한글 33자';
COMMENT ON COLUMN "BOARD"."CONTENT" IS '한글 666자';
COMMENT ON COLUMN "BOARD"."BOARD_STATUS" IS 
'Y - 정상 게시 
D - 작성자가 삭제 
B - 관리자가 블락 / 블라인드';
COMMENT ON COLUMN "BOARD"."BOARD_CATEGORY" IS 'N - 일반
S - 중고
A - 입양
M - 실종';
COMMENT ON COLUMN "BOARD"."DETAIL_STATUS" IS 
'P - 진행중(판매중, 분양중, 찾는중)
D - 완료상태
N - 무상태(일반)';

-- BOARD_IMG
COMMENT ON COLUMN "BOARD_IMG"."IMG_NO" IS 'SEQ_BOARD_IMG';
COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '이미지가 첨부된 게시글 번호';
COMMENT ON COLUMN "BOARD_IMG"."ORIGIN_NAME" IS '이미지 원래 이름 경로';
COMMENT ON COLUMN "BOARD_IMG"."CHAGNE_NAME" IS '이미지 바뀐 이름 경로';

-- CHAT_ROOM
COMMENT ON COLUMN "CHAT_ROOM"."CHAT_ROOM_NO" IS 'SEQ_CHAT_ROOM';
COMMENT ON COLUMN "CHAT_ROOM"."USER_NO" IS '회원번호';
COMMENT ON COLUMN "CHAT_ROOM"."STATUS" IS 
'Y - 활성화 
N - 한명 나감';

-- COMMENT
COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS 'SEQ_COMMENT';
COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '댓글이 달린 게시글 번호';
COMMENT ON COLUMN "COMMENT"."USER_NO" IS '댓글을 단 회원번호';
COMMENT ON COLUMN "COMMENT"."CONTENT" IS '한글 33자';
COMMENT ON COLUMN "COMMENT"."STATUS" IS 
'Y - 정상 게시 
D - 작성자가 삭제
B - 관리자가 블락 / 블라인드';

-- DOG
COMMENT ON COLUMN "DOG"."DOG_NO" IS 'SEQ_DOG';
COMMENT ON COLUMN "DOG"."USER_NO" IS '반려견 주인의 회원번호';
COMMENT ON COLUMN "DOG"."BREED" IS 
'견종 직접 작성 가능
(디폴트 모름)';
COMMENT ON COLUMN "DOG"."GENDER" IS 
'성별 선택
M - 수컷
F - 암컷
N - 모름';
COMMENT ON COLUMN "DOG"."NOTE" IS '한글 333자';
COMMENT ON COLUMN "DOG"."PROFILE_NO" IS '프사는 하나만 가능';

-- HISTORY
COMMENT ON COLUMN "HISTORY"."HISTORY_NO" IS 'SEQ_HISTORY';
COMMENT ON COLUMN "HISTORY"."USER_NO" IS '포인트 받은 회원번호';
COMMENT ON COLUMN "HISTORY"."POINT" IS 
'회원가입 - 500점
로그인 - 100점 (24시 기준)
게시글 작성 - 100점
댓글 작성 - 50점
이벤트 - 50 ~ 500점';

-- INFO
COMMENT ON COLUMN "INFO"."INFO_NO" IS 'SEQ_INFO';
COMMENT ON COLUMN "INFO"."CONTENT" IS '정보글 내용 (한글 666자)';
COMMENT ON COLUMN "INFO"."INFO_IMG" IS 
'정보글 이미지 경로
(관리자 등록이라 바뀐이름 노필요)';

-- LIKE
COMMENT ON COLUMN "LIKE"."LIKE_NO" IS 'SEQ_LIKE';
COMMENT ON COLUMN "LIKE"."USER_NO" IS '좋아요를 한 회원번호';
COMMENT ON COLUMN "LIKE"."LIKE_TYPE" IS 
'B - 게시글
I - 정보글';
COMMENT ON COLUMN "LIKE"."BOARD_NO" IS '좋아요 한 게시글 번호';
COMMENT ON COLUMN "LIKE"."INFO_NO" IS '좋아요 한 정보글 번호';
COMMENT ON COLUMN "LIKE"."ITEM_NO" IS '좋아요한 상품 번호';

-- MEMO
COMMENT ON COLUMN "MEMO"."MEMO_NO" IS 'SEQ_MEMO';
COMMENT ON COLUMN "MEMO"."USER_NO" IS '메모 작성한 회원번호';
COMMENT ON COLUMN "MEMO"."CONTENT" IS '한글 66자';

-- MESSAGE
COMMENT ON COLUMN "MESSAGE"."MESSAGE_NO" IS 'SEQ_MESSAGE';
COMMENT ON COLUMN "MESSAGE"."USER_NO" IS '메세지 보낸 회원번호';
COMMENT ON COLUMN "MESSAGE"."CONTENT" IS '한글 666자(빈 메세지 X)';
COMMENT ON COLUMN "MESSAGE"."MESSAGE_DATE" IS '메세지 발송 시간';

-- NOTICE
COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS 'SEQ_NOTICE';
COMMENT ON COLUMN "NOTICE"."CONTENT" IS '정보글 내용 (한글 666자)';
COMMENT ON COLUMN "NOTICE"."INFO_IMG" IS 
'정보글 이미지 경로
(관리자 등록이라 바뀐이름 노필요)';

-- PRODUCT
COMMENT ON COLUMN "PRODUCT"."PRODUCT_NO" IS 'SEQ_PRODUCT';
COMMENT ON COLUMN "PRODUCT"."CONTENT" IS '한글 333자';
COMMENT ON COLUMN "PRODUCT"."STATUS" IS 
'Y - 교환 가능 
N - 불가능';

-- PROFILE_IMG
COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_NO" IS 'SEQ_PROFILE_IMG';
COMMENT ON COLUMN "PROFILE_IMG"."ORIGIN_NAME" IS '프사 원래 이름 경로';
COMMENT ON COLUMN "PROFILE_IMG"."CHANGE_NAME" IS '바뀐 이름 경로';

-- REPLY
COMMENT ON COLUMN "REPLY"."REPLY_NO" IS 'SEQ_REPLY';
COMMENT ON COLUMN "REPLY"."COMMENT_NO" IS '대댓글이 달린 댓글 번호';
COMMENT ON COLUMN "REPLY"."USER_NO" IS '대댓글을 단 회원번호';
COMMENT ON COLUMN "REPLY"."CONTENT" IS '한글 33자';
COMMENT ON COLUMN "REPLY"."STATUS" IS 
'Y - 정상 게시 
D - 작성자가 삭제 
B - 관리자가 블락 / 블라인드';

-- REPORT
COMMENT ON COLUMN "REPORT"."REPORT_NO" IS 'SEQ_REPORT';
COMMENT ON COLUMN "REPORT"."USER_NO" IS '신고한 회원번호';
COMMENT ON COLUMN "REPORT"."CATEGORY" IS 
'욕설
음란
광고
부적절
기타';
COMMENT ON COLUMN "REPORT"."CONTENT" IS '한글 666자';
COMMENT ON COLUMN "REPORT"."REPORT_TYPE" IS 
'C - 댓글(COMMENT)
R - 대댓글(REPLY)
B - 게시글(BOARD)';
COMMENT ON COLUMN "REPORT"."BOARD_NO" IS '신고한 게시글 번호';
COMMENT ON COLUMN "REPORT"."CHAT_ROOM_NO" IS '채팅방 자체 신고(메세지 따로 신고X)';
COMMENT ON COLUMN "REPORT"."COMMENT_NO" IS '신고한 댓글 번호';
COMMENT ON COLUMN "REPORT"."REPLY_NO" IS '신고한 대댓글 번호';

-- USER
COMMENT ON COLUMN "USER"."USER_NO" IS 'SEQ_USER';
COMMENT ON COLUMN "USER"."EMAIL" IS '유니크 추가';
COMMENT ON COLUMN "USER"."NICK_NAME" IS '유니크 추가';
COMMENT ON COLUMN "USER"."PHONE" IS '유니크 추가';
COMMENT ON COLUMN "USER"."STATUS" IS 
'Y - 활동
N - 탈퇴
B - 블랙리스트
V - 휴면';
COMMENT ON COLUMN "USER"."PROFILE_NO" IS '프사는 하나만 가능';

COMMIT;

--INSERT INTO "USER"
--VALUES (
--SEQ_USER.NEXTVAL, 
--'SAMPLE@NAVER.COM', 
--1234, 
--'박재현', 
--'박재현', 
--'010-4233-9839', 
--'서울', 
--DEFAULT,
--DEFAULT,
--DEFAULT,
--DEFAULT,
--NULL
--);



