DROP TABLE "ALARM" CASCADE CONSTRAINTS;
DROP TABLE "ASK" CASCADE CONSTRAINTS;
DROP TABLE "AUTHORITY" CASCADE CONSTRAINTS;
DROP TABLE "BOARD" CASCADE CONSTRAINTS;
DROP TABLE "BOARD_IMG" CASCADE CONSTRAINTS;
DROP TABLE "BOARD_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "CHAT_ROOM" CASCADE CONSTRAINTS;
DROP TABLE "COMMENT" CASCADE CONSTRAINTS;
DROP TABLE "DOG" CASCADE CONSTRAINTS;
DROP TABLE "HISTORY" CASCADE CONSTRAINTS;
DROP TABLE "IMG_DOG" CASCADE CONSTRAINTS;
DROP TABLE "IMG_USER" CASCADE CONSTRAINTS;
DROP TABLE "LIKE" CASCADE CONSTRAINTS;
DROP TABLE "MEMO" CASCADE CONSTRAINTS;
DROP TABLE "MESSAGE" CASCADE CONSTRAINTS;
DROP TABLE "PRODUCT" CASCADE CONSTRAINTS;
DROP TABLE "REPORT" CASCADE CONSTRAINTS;
DROP TABLE "TYPE" CASCADE CONSTRAINTS;
DROP TABLE "USER" CASCADE CONSTRAINTS;
DROP TABLE "USER_SOCIAL" CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_ALARM;
DROP SEQUENCE SEQ_ASK;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_BOARD_IMG;
DROP SEQUENCE SEQ_CHAT_ROOM;
DROP SEQUENCE SEQ_COMMENT;
DROP SEQUENCE SEQ_DOG;
DROP SEQUENCE SEQ_HISTORY;
DROP SEQUENCE SEQ_LIKE;
DROP SEQUENCE SEQ_MEMO;
DROP SEQUENCE SEQ_MESSAGE;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_REPORT;
DROP SEQUENCE SEQ_USER;

CREATE SEQUENCE SEQ_ALARM;
CREATE SEQUENCE SEQ_ASK;
CREATE SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_BOARD_IMG;
CREATE SEQUENCE SEQ_CHAT_ROOM;
CREATE SEQUENCE SEQ_COMMENT;
CREATE SEQUENCE SEQ_DOG;
CREATE SEQUENCE SEQ_HISTORY;
CREATE SEQUENCE SEQ_LIKE;
CREATE SEQUENCE SEQ_MEMO;
CREATE SEQUENCE SEQ_MESSAGE;
CREATE SEQUENCE SEQ_PRODUCT;
CREATE SEQUENCE SEQ_REPORT;
CREATE SEQUENCE SEQ_USER START WITH 11;

-------------------- CREATE TABLE --------------------
CREATE TABLE "ALARM" (
	"ALARM_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"FROM_USER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(1000)	DEFAULT '새로운 알림'	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"ALARM_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"TYPE_CODE"	CHAR(1)		NOT NULL,
	"REF_NO"	NUMBER		NOT NULL
);

CREATE TABLE "ASK" (
	"ASK_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(2000)		NOT NULL,
	"RES_CONTENT"	VARCHAR2(2000)		NULL,
	"STATUS"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"ASK_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"RES_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"TITLE"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "AUTHORITY" (
    "USER_NO" NUMBER NOT NULL,
    "AUTHORITY" VARCHAR2(20) NOT NULL
);

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(100)		NOT NULL,
	"CONTENT"	VARCHAR2(2000)		NOT NULL,
	"BOARD_CODE"	CHAR(1)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"VIEWS"	NUMBER	DEFAULT 0	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"DETAIL_STATUS"	CHAR(1)		NULL,
	"LIKES"	NUMBER	DEFAULT 0	NOT NULL
);

CREATE TABLE "BOARD_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(100)		NULL,
	"CHANGE_NAME"	VARCHAR2(100)		NULL
);

CREATE TABLE "BOARD_TYPE" (
	"BOARD_CODE"	CHAR(1)		NOT NULL,
	"BOARD_NAME"	VARCHAR2(10)		NOT NULL
);

CREATE TABLE "CHAT_ROOM" (
	"CHAT_ROOM_NO"	NUMBER		NOT NULL,
	"FROM_USER_NO"	NUMBER		NOT NULL,
	"FROM_STATUS"	CHAR(1)		NULL,
	"TO_USER_NO"	NUMBER		NOT NULL,
	"TO_STATUS"	CHAR(1)		NULL
);

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(100)		NOT NULL,
	"COMMENT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NULL,
	"REF_NO"	NUMBER		NULL
);

CREATE TABLE "DOG" (
	"DOG_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"IS_MAIN"	CHAR(1)	DEFAULT 'N'	NULL,
	"DOG_NAME"	VARCHAR2(50)		NOT NULL,
	"BREED"	VARCHAR2(50)	DEFAULT '모름'	NOT NULL,
	"GENDER"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BIRTHDAY"	DATE		NULL,
	"NOTE"	VARCHAR2(1000)		NULL
);

CREATE TABLE "HISTORY" (
	"HISTORY_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"POINT"	NUMBER	DEFAULT 0	NOT NULL,
	"POINT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CONTENT"	VARCHAR2(200)		NULL
);

CREATE TABLE "IMG_DOG" (
	"DOG_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(100)		NULL,
	"CHANGE_NAME"	VARCHAR2(100)		NULL
);

CREATE TABLE "IMG_USER" (
	"USER_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(100)		NULL,
	"CHANGE_NAME"	VARCHAR2(100)		NULL
);

CREATE TABLE "LIKE" (
	"LIKE_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"TYPE_CODE"	CHAR(1)		NOT NULL,
	"REF_NO"	NUMBER		NOT NULL
);

CREATE TABLE "MEMO" (
	"MEMO_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(200)		NOT NULL,
	"TARGET_DATE"	DATE		NULL
);

CREATE TABLE "MESSAGE" (
	"MESSAGE_NO"	NUMBER		NOT NULL,
	"CHAT_ROOM_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(2000)		NOT NULL,
	"MESSAGE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

CREATE TABLE "PRODUCT" (
	"PRODUCT_NO"	NUMBER		NOT NULL,
	"PRICE"	NUMBER		NOT NULL,
	"QTY"	NUMBER	DEFAULT 0	NOT NULL,
	"TITLE"	VARCHAR2(100)		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NULL,
	"STATUS"	CHAR(2)	DEFAULT 'Y'	NOT NULL,
	"LIKES"	NUMBER	DEFAULT 0	NOT NULL,
	"IMG"	VARCHAR2(100)		NULL
);

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"CATEGORY"	VARCHAR2(100)		NOT NULL,
	"CONTENT"	VARCHAR2(2000)		NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"TYPE_CODE"	CHAR(1)		NOT NULL,
	"REF_NO"	NUMBER		NOT NULL
);

CREATE TABLE "TYPE" (
	"TYPE_CODE"	CHAR(1)		NOT NULL,
	"TYPE_NAME"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "USER" (
	"USER_NO"	NUMBER		NOT NULL,
	"EMAIL"	VARCHAR2(100)		NOT NULL,
	"PWD"	VARCHAR2(500)		NOT NULL,
	"USER_NAME"	VARCHAR2(50)		NULL,
	"NICK_NAME"	VARCHAR2(50)		NOT NULL,
	"PHONE"	VARCHAR2(13)		 NULL,
	"ADDRESS"	VARCHAR2(1000)		NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"POINTS"	NUMBER	DEFAULT 0	NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL
);

CREATE TABLE "USER_SOCIAL" (
    "SOCIAL_ID" VARCHAR2(50CHAR) NOT NULL,
    "USER_NO" NUMBER NOT NULL,
    "SOCIAL_TYPE" VARCHAR2(20CHAR) NOT NULL
);


-------------------- CONSTRAINT --------------------
-------------------- PK --------------------
ALTER TABLE "ALARM" ADD CONSTRAINT "PK_ALARM" PRIMARY KEY (
	"ALARM_NO"
);
ALTER TABLE "ASK" ADD CONSTRAINT "PK_ASK" PRIMARY KEY (
	"ASK_NO"
);
ALTER TABLE "AUTHORITY" ADD CONSTRAINT "PK_AUTHORITY" PRIMARY KEY (
    "USER_NO", "AUTHORITY"
);
ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);
ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"IMG_NO"
);
ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"BOARD_CODE"
);
ALTER TABLE "CHAT_ROOM" ADD CONSTRAINT "PK_CHAT_ROOM" PRIMARY KEY (
	"CHAT_ROOM_NO"
);
ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);
ALTER TABLE "DOG" ADD CONSTRAINT "PK_DOG" PRIMARY KEY (
	"DOG_NO"
);
ALTER TABLE "HISTORY" ADD CONSTRAINT "PK_HISTORY" PRIMARY KEY (
	"HISTORY_NO"
);
ALTER TABLE "IMG_DOG" ADD CONSTRAINT "PK_IMG_DOG" PRIMARY KEY (
	"DOG_NO"
);
ALTER TABLE "IMG_USER" ADD CONSTRAINT "PK_IMG_USER" PRIMARY KEY (
	"USER_NO"
);
ALTER TABLE "LIKE" ADD CONSTRAINT "PK_LIKE" PRIMARY KEY (
	"LIKE_NO"
);
ALTER TABLE "MEMO" ADD CONSTRAINT "PK_MEMO" PRIMARY KEY (
	"MEMO_NO"
);
ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
	"MESSAGE_NO"
);
ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRODUCT_NO"
);
ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);
ALTER TABLE "TYPE" ADD CONSTRAINT "PK_TYPE" PRIMARY KEY (
	"TYPE_CODE"
);
ALTER TABLE "USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY (
	"USER_NO"
);
ALTER TABLE "USER_SOCIAL" ADD CONSTRAINT "PK_USER_SOCIAL" PRIMARY KEY (
    "SOCIAL_ID"
);

-------------------- FK --------------------
----- ALARM
ALTER TABLE "ALARM" ADD CONSTRAINT "FK_USER_TO_ALARM_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
ALTER TABLE "ALARM" ADD CONSTRAINT "FK_USER_TO_ALARM_2" FOREIGN KEY (
	"FROM_USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
ALTER TABLE "ALARM" ADD CONSTRAINT "FK_TYPE_TO_ALARM_1" FOREIGN KEY (
	"TYPE_CODE"
)
REFERENCES "TYPE" (
	"TYPE_CODE"
);
----- ASK
ALTER TABLE "ASK" ADD CONSTRAINT "FK_USER_TO_ASK_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- AUTHORITY
ALTER TABLE "AUTHORITY" ADD CONSTRAINT "FK_USER_TO_AUTHORITY_1" FOREIGN KEY (
    "USER_NO"
)
REFERENCES "USER" (
    "USER_NO"
);
----- BOARD
ALTER TABLE "BOARD" ADD CONSTRAINT "FK_USER_TO_BOARD_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_1" FOREIGN KEY (
	"BOARD_CODE"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_CODE"
);
----- BOARD_IMG
ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);
----- CHAT_ROOM
ALTER TABLE "CHAT_ROOM" ADD CONSTRAINT "FK_USER_TO_CHAT_ROOM_1" FOREIGN KEY (
	"FROM_USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
ALTER TABLE "CHAT_ROOM" ADD CONSTRAINT "FK_USER_TO_CHAT_ROOM_2" FOREIGN KEY (
	"TO_USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- COMMENT
ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);
ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_USER_TO_COMMENT_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_1" FOREIGN KEY (
	"REF_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);
----- DOG
ALTER TABLE "DOG" ADD CONSTRAINT "FK_USER_TO_DOG_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- HISTORY
ALTER TABLE "HISTORY" ADD CONSTRAINT "FK_USER_TO_HISTORY_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- IMG_DOG
ALTER TABLE "IMG_DOG" ADD CONSTRAINT "FK_DOG_TO_IMG_DOG_1" FOREIGN KEY (
	"DOG_NO"
)
REFERENCES "DOG" (
	"DOG_NO"
);
----- IMG_USER
ALTER TABLE "IMG_USER" ADD CONSTRAINT "FK_USER_TO_IMG_USER_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- LIKE
ALTER TABLE "LIKE" ADD CONSTRAINT "FK_USER_TO_LIKE_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
ALTER TABLE "LIKE" ADD CONSTRAINT "FK_TYPE_TO_LIKE_1" FOREIGN KEY (
	"TYPE_CODE"
)
REFERENCES "TYPE" (
	"TYPE_CODE"
);
----- MEMO
ALTER TABLE "MEMO" ADD CONSTRAINT "FK_USER_TO_MEMO_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- MESSAGE
ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_CHAT_ROOM_TO_MESSAGE_1" FOREIGN KEY (
	"CHAT_ROOM_NO"
)
REFERENCES "CHAT_ROOM" (
	"CHAT_ROOM_NO"
);
ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_USER_TO_MESSAGE_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
----- REPORT
ALTER TABLE "REPORT" ADD CONSTRAINT "FK_USER_TO_REPORT_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
ALTER TABLE "REPORT" ADD CONSTRAINT "FK_TYPE_TO_REPORT_1" FOREIGN KEY (
	"TYPE_CODE"
)
REFERENCES "TYPE" (
	"TYPE_CODE"
);
----- USER_SOCIAL
ALTER TABLE "USER_SOCIAL" ADD CONSTRAINT "FK_USER_TO_USER_SOCIAL_1" FOREIGN KEY (
    "USER_NO"
)
REFERENCES "USER" (
    "USER_NO"
);

-------------------- COMMENT --------------------
-- ALARM
COMMENT ON COLUMN "ALARM"."ALARM_NO" IS 'SEQ_ALARM';
COMMENT ON COLUMN "ALARM"."USER_NO" IS '알람 받을 회원 번호';
COMMENT ON COLUMN "ALARM"."FROM_USER_NO" IS '알람을 발생시킨 회원 번호';
COMMENT ON COLUMN "ALARM"."CONTENT" IS '한글 333자';
COMMENT ON COLUMN "ALARM"."STATUS" IS 
'N - 안읽음
Y - 읽음';
COMMENT ON COLUMN "ALARM"."ALARM_DATE" IS '알람 발생 시간';
COMMENT ON COLUMN "ALARM"."TYPE_CODE" IS 'B, C, L, M, R, P';

-- ASK
COMMENT ON COLUMN "ASK"."ASK_NO" IS 'SEQ_ASK';
COMMENT ON COLUMN "ASK"."USER_NO" IS '문의한 회원 번호';
COMMENT ON COLUMN "ASK"."CONTENT" IS '한글 666자';
COMMENT ON COLUMN "ASK"."STATUS" IS 
'Y - 답변완료
N - 미완료';
COMMENT ON COLUMN "ASK"."TITLE" IS '한글 33자';

-- BOARD
COMMENT ON COLUMN "BOARD"."BOARD_NO" IS 'SEQ_BOARD';
COMMENT ON COLUMN "BOARD"."USER_NO" IS '게시글 작성한 회원 번호';
COMMENT ON COLUMN "BOARD"."TITLE" IS '한글 33자';
COMMENT ON COLUMN "BOARD"."CONTENT" IS '한글 666자';
COMMENT ON COLUMN "BOARD"."BOARD_CODE" IS 'C, S, A, M, I, E,  N';
COMMENT ON COLUMN "BOARD"."STATUS" IS 
'Y - 정상 게시
D - 작성자가 삭제
B - 관리자가 블락 / 블라인드';
COMMENT ON COLUMN "BOARD"."DETAIL_STATUS" IS 
'P - 진행중(판매중, 분양중, 찾는중)
D - 완료상태
N - 무상태(일반)';

-- BOARD_IMG
COMMENT ON COLUMN "BOARD_IMG"."IMG_NO" IS 'SEQ_BOARD_IMG';
COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '이미지가 첨부된 게시글 번호';
COMMENT ON COLUMN "BOARD_IMG"."ORIGIN_NAME" IS '이미지 원래 이름 경로';
COMMENT ON COLUMN "BOARD_IMG"."CHANGE_NAME" IS '이미지 바뀐 이름 경로';

-- BOARD_TYPE
COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CODE" IS 'C, S, A, M, I, E,  N';
COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NAME" IS '일반, 중고, 입양, 실종, 정보, 이벤, 공지';

-- CHAT_ROOM
COMMENT ON COLUMN "CHAT_ROOM"."CHAT_ROOM_NO" IS 'SEQ_CHAT_ROOM';
COMMENT ON COLUMN "CHAT_ROOM"."FROM_USER_NO" IS '요청 보낸 회원 번호';
COMMENT ON COLUMN "CHAT_ROOM"."FROM_STATUS" IS 'Y - 있음 N - 나감';
COMMENT ON COLUMN "CHAT_ROOM"."TO_USER_NO" IS '요청 받은 회원 번호';
COMMENT ON COLUMN "CHAT_ROOM"."TO_STATUS" IS 'Y - 있음 N - 나감';

-- COMMENT
COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS 'SEQ_COMMENT';
COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '댓글이 달린 게시글 번호';
COMMENT ON COLUMN "COMMENT"."USER_NO" IS '댓글을 단 회원번호';
COMMENT ON COLUMN "COMMENT"."CONTENT" IS '한글 33자(빈 댓글x)';
COMMENT ON COLUMN "COMMENT"."STATUS" IS 
'Y - 정상 게시 
D - 작성자가 삭제
B - 관리자가 블락 / 블라인드';
COMMENT ON COLUMN "COMMENT"."REF_NO" IS '대댓글이 달린 댓글 번호';

-- DOG
COMMENT ON COLUMN "DOG"."DOG_NO" IS 'SEQ_DOG';
COMMENT ON COLUMN "DOG"."USER_NO" IS '반려견 주인의 회원번호';
COMMENT ON COLUMN "DOG"."BREED" IS 
'견종 직접 작성 가능
(디폴트 모름)';
COMMENT ON COLUMN "DOG"."GENDER" IS 
'성별 선택
M - 수컷
F - 암컷
N - 모름';
COMMENT ON COLUMN "DOG"."NOTE" IS '한글 333자';

-- HISTORY
COMMENT ON COLUMN "HISTORY"."HISTORY_NO" IS 'SEQ_HISTORY';
COMMENT ON COLUMN "HISTORY"."USER_NO" IS '포인트 받은 회원번호';
COMMENT ON COLUMN "HISTORY"."POINT" IS 
'회원가입 - 500점
로그인 - 100점 (24시 기준)
게시글 작성 - 100점
댓글 작성 - 50점
이벤트 - 50 ~ 500점';

-- IMG_DOG
COMMENT ON COLUMN "IMG_DOG"."DOG_NO" IS 'SEQ_DOG';
COMMENT ON COLUMN "IMG_DOG"."ORIGIN_NAME" IS '반려견 프사 원래 이름';
COMMENT ON COLUMN "IMG_DOG"."CHANGE_NAME" IS '바뀐 이름 경로';

-- IMG_USER
COMMENT ON COLUMN "IMG_USER"."USER_NO" IS 'SEQ_USER';
COMMENT ON COLUMN "IMG_USER"."ORIGIN_NAME" IS '회원 프사 원래 이름 경로';
COMMENT ON COLUMN "IMG_USER"."CHANGE_NAME" IS '바뀐 이름 경로';

-- LIKE
COMMENT ON COLUMN "LIKE"."LIKE_NO" IS 'SEQ_LIKE';
COMMENT ON COLUMN "LIKE"."USER_NO" IS '좋아요를 한 회원번호';
COMMENT ON COLUMN "LIKE"."TYPE_CODE" IS 'B, P';
COMMENT ON COLUMN "LIKE"."REF_NO" IS '게시글, 상품';

-- MEMO
COMMENT ON COLUMN "MEMO"."MEMO_NO" IS 'SEQ_MEMO';
COMMENT ON COLUMN "MEMO"."USER_NO" IS '메모 작성한 회원번호';
COMMENT ON COLUMN "MEMO"."CONTENT" IS '한글 66자';

-- MESSAGE
COMMENT ON COLUMN "MESSAGE"."MESSAGE_NO" IS 'SEQ_MESSAGE';
COMMENT ON COLUMN "MESSAGE"."USER_NO" IS '메세지 보낸 회원번호';
COMMENT ON COLUMN "MESSAGE"."CONTENT" IS '한글 666자(빈 메세지 X)';
COMMENT ON COLUMN "MESSAGE"."MESSAGE_DATE" IS '메세지 발송 시간';

-- PRODUCT
COMMENT ON COLUMN "PRODUCT"."PRODUCT_NO" IS 'SEQ_PRODUCT';
COMMENT ON COLUMN "PRODUCT"."CONTENT" IS '한글 333자';
COMMENT ON COLUMN "PRODUCT"."STATUS" IS 
'Y - 교환 가능 
N - 불가능';
COMMENT ON COLUMN "PRODUCT"."IMG" IS '상품 이미지만 따로 관리하는 컬럼';

-- REPORT
COMMENT ON COLUMN "REPORT"."REPORT_NO" IS 'SEQ_REPORT';
COMMENT ON COLUMN "REPORT"."USER_NO" IS '신고한 회원번호';
COMMENT ON COLUMN "REPORT"."CATEGORY" IS 
'욕설
음란
광고
부적절
기타';
COMMENT ON COLUMN "REPORT"."CONTENT" IS '한글 666자';
COMMENT ON COLUMN "REPORT"."TYPE_CODE" IS 'B, C, L, M, R, P';

-- TYPE
COMMENT ON COLUMN "TYPE"."TYPE_CODE" IS 'B, C, L, M, R, P';
COMMENT ON COLUMN "TYPE"."TYPE_NAME" IS '게시글, 댓글, 좋아요, 채팅방, 문의 답변, 상품';

-- USER
COMMENT ON COLUMN "USER"."USER_NO" IS 'SEQ_USER';
COMMENT ON COLUMN "USER"."EMAIL" IS '유니크 추가';
COMMENT ON COLUMN "USER"."NICK_NAME" IS '유니크 추가';
COMMENT ON COLUMN "USER"."PHONE" IS '유니크 추가';
COMMENT ON COLUMN "USER"."STATUS" IS 
'Y - 활동
N - 탈퇴
B - 블랙리스트
V - 휴면';


-- 데이터
INSERT INTO "BOARD_TYPE"
VALUES ('C', '일반');
INSERT INTO "BOARD_TYPE"
VALUES ('S', '중고');
INSERT INTO "BOARD_TYPE"
VALUES ('A', '입양');
INSERT INTO "BOARD_TYPE"
VALUES ('M', '실종');
INSERT INTO "BOARD_TYPE"
VALUES ('I', '정보');
INSERT INTO "BOARD_TYPE"
VALUES ('E', '이벤');
INSERT INTO "BOARD_TYPE"
VALUES ('N', '공지');

INSERT INTO "TYPE"
VALUES ('B', '게시글');
INSERT INTO "TYPE"
VALUES ('C', '댓글');
INSERT INTO "TYPE"
VALUES ('L', '좋아요');
INSERT INTO "TYPE"
VALUES ('M', '채팅방');
INSERT INTO "TYPE"
VALUES ('R', '문의답변');
INSERT INTO "TYPE"
VALUES ('P', '상품');


COMMIT;